on:
  workflow_dispatch:
  schedule:
    # run every 4 hours
    - cron: '20 */4 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.SCOOP_GH_TOKEN }}
          SCOOP_REPO: 'https://github.com/brian6932/Scoop'
          SCOOP_BRANCH: '64bit-v2-v3-v4'
          SKIP_UPDATED: 1
