on:
  issues:
    types: [opened, labeled]
name: Issues
jobs:
  issueHandler:
    name: IssueHandler
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: IssueHandler
        uses: ScoopInstaller/GithubActions@main
        if: github.event.action == 'opened' || (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'verify'))
        env:
          SCOOP_REPO: 'https://github.com/brian6932/Scoop'
          SCOOP_BRANCH: '64bit-v2-v3-v4'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
