on:
  pull_request:
    types: [opened]
name: Pull Requests
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: PullRequestHandler
        uses: ScoopInstaller/GithubActions@main
        env:
          SCOOP_REPO: 'https://github.com/brian6932/Scoop'
          SCOOP_BRANCH: '64bit-v2-v3-v4'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
